on: [push]
jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build draft PDF
        uses: tarleb/openjournals-draft-action@master
        with:
          paper-path: docs/joss/paper.md
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          name: paper
          path: docs/joss/paper-${{ github.sha }}.pdf
